In [5]:
import pandas as pd
import numpy as np
import sklearn.metrics as smt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [6]:
df = load_digits()
df

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [7]:
x=df.data
y=df.target

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=50,test_size=0.2)

In [10]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)

In [15]:
print("Classification Accuracy : ",smt.accuracy_score(y_test,y_pred)*100)

Classification Accuracy :  94.44444444444444


In [27]:
y_pred_proba = logreg.predict_proba(x_test) #probabilites of y_pred
print("Logrithmic Loss:",smt.log_loss(y_test,y_pred_proba))

Logrithmic Loss: 0.2132481502676374


In [24]:
print("R2 Metrics:",smt.r2_score(y_test,y_pred))

R2 Metrics: 0.8175914135784247


In [16]:
print("Mean absolute error : ",smt.mean_absolute_error(y_test,y_pred))

Mean absolute error :  0.275


In [17]:
print("Mean squared error : ",smt.mean_squared_error(y_test,y_pred))

Mean squared error :  1.5972222222222223


In [19]:
print("Confusion Matrix:\n",smt.confusion_matrix(y_test,y_pred))

Confusion Matrix:
 [[40  0  0  0  0  0  0  0  1  0]
 [ 0 38  0  0  0  0  0  0  4  0]
 [ 0  1 44  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  2  1  1]
 [ 0  1  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 28  0  0  0  3]
 [ 0  0  0  0  0  0 38  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  2  0  1  0  0  0  0 25  0]
 [ 0  0  0  1  0  0  0  0  1 38]]


In [11]:
print("Classification report:\n",smt.classification_report(y_test,y_pred))

Classification report:
              precision    recall  f1-score   support

          0       1.00      0.98      0.99        41
          1       0.90      0.90      0.90        42
          2       1.00      0.98      0.99        45
          3       0.93      0.86      0.89        29
          4       1.00      0.97      0.98        31
          5       1.00      0.90      0.95        31
          6       1.00      1.00      1.00        38
          7       0.94      0.97      0.96        35
          8       0.78      0.89      0.83        28
          9       0.88      0.95      0.92        40

avg / total       0.95      0.94      0.95       360

