# Question 1

Total number of favourable outcomes is 5 ( which is the number of times 'Sunny' occured in weather column)
Out of which there are only 3 days when play was 'Yes'. 
Therefore,

P(Yes/Sunny)=3/5

# Question 2

In [15]:
import pandas as pd
import numpy as np

In [32]:
ds= pd.read_csv('iris.csv')
ds.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [30]:
tar=ds['Species']
ds['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [31]:
c=0
target=[]
for i in tar:
    if i=='Iris-setosa': 
        target.append(0)
    elif i=='Iris-versicolor': 
        target.append(1)
    else: target.append(2)
    c=+1

print(target)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [40]:
ds.drop(['Id'],axis=1,inplace=True)
ds.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [63]:
features=ds.drop(['Species'],axis=1)
features.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [49]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.model_selection import train_test_split

In [50]:
mul = MultinomialNB()
gaus = GaussianNB()

In [51]:
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [52]:
mul.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [53]:
predict_mul=mul.predict(x_test)

In [55]:
gaus.fit(x_train,y_train)

GaussianNB(priors=None)

In [57]:
predict_gaus=gaus.predict(x_test)

In [58]:
from sklearn.metrics import classification_report,confusion_matrix

In [59]:
print(classification_report(y_test,predict_mul))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.75      1.00      0.86         9
          2       1.00      0.73      0.84        11

avg / total       0.93      0.90      0.90        30



In [61]:
print(confusion_matrix(y_test,predict_mul))

[[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]


In [60]:
print(classification_report(y_test,predict_gaus))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [62]:
print(confusion_matrix(y_test,predict_gaus))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
