In [1]:
import pandas as pd
import numpy as np
import sklearn.metrics as smt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [2]:
from sklearn.datasets import load_digits
dig = load_digits()

In [3]:
dig

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [4]:
x = dig.data
y = dig.target

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [10]:
svc = SVC(kernel='linear')
svc.fit(x_train,y_train)
pred_y = svc.predict(x_test)
print("SVM when Kernel = 'LINEAR':-\n")
print("Classification Report : \n",smt.classification_report(y_test,pred_y))
print("Confusion Matrix : \n",smt.confusion_matrix(y_test,pred_y))

SVM when Kernel = 'LINEAR':-

Classification Report : 
              precision    recall  f1-score   support

          0       1.00      0.98      0.99        41
          1       0.95      0.98      0.96        42
          2       1.00      1.00      1.00        45
          3       0.97      0.97      0.97        29
          4       0.97      1.00      0.98        31
          5       1.00      0.90      0.95        31
          6       1.00      1.00      1.00        38
          7       1.00      0.97      0.99        35
          8       0.96      0.93      0.95        28
          9       0.91      1.00      0.95        40

avg / total       0.98      0.97      0.98       360

Confusion Matrix : 
 [[40  0  0  0  1  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  1  0]
 [ 0  0 45  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  0  0  1]
 [ 0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  1  0 28  0  0  0  2]
 [ 0  0  0  0  0  0 38  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  2  0  0  0  0 

In [12]:
svc = SVC(kernel='poly', degree=10)
svc.fit(x_train,y_train)
pred_y = svc.predict(x_test)
print("SVM when Kernel = 'POLY':-\n")
print("Classification Report : \n",smt.classification_report(y_test,pred_y))
print("Confusion Matrix : \n",smt.confusion_matrix(y_test,pred_y))

SVM when Kernel = 'POLY':-

Classification Report : 
              precision    recall  f1-score   support

          0       1.00      0.95      0.97        41
          1       0.95      0.93      0.94        42
          2       1.00      1.00      1.00        45
          3       0.96      0.93      0.95        29
          4       0.94      1.00      0.97        31
          5       0.97      0.97      0.97        31
          6       0.97      1.00      0.99        38
          7       0.97      0.94      0.96        35
          8       0.93      0.93      0.93        28
          9       0.95      1.00      0.98        40

avg / total       0.97      0.97      0.97       360

Confusion Matrix : 
 [[39  0  0  0  1  0  1  0  0  0]
 [ 0 39  0  0  1  0  0  0  2  0]
 [ 0  0 45  0  0  0  0  0  0  0]
 [ 0  0  0 27  0  1  0  1  0  0]
 [ 0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  1]
 [ 0  0  0  0  0  0 38  0  0  0]
 [ 0  1  0  0  0  0  0 33  0  1]
 [ 0  1  0  1  0  0  0

In [13]:
svc = SVC(kernel='rbf')
svc.fit(x_train,y_train)
pred_y = svc.predict(x_test)
print("SVM when Kernel = 'GAUSSIAN':-\n")
print("Classification Report : \n",smt.classification_report(y_test,pred_y))
print("Confusion Matrix : \n",smt.confusion_matrix(y_test,pred_y))

SVM when Kernel = 'GAUSSIAN':-

Classification Report : 
              precision    recall  f1-score   support

          0       1.00      0.37      0.54        41
          1       1.00      0.24      0.38        42
          2       1.00      0.20      0.33        45
          3       0.12      1.00      0.22        29
          4       1.00      0.65      0.78        31
          5       1.00      0.74      0.85        31
          6       1.00      0.55      0.71        38
          7       1.00      0.37      0.54        35
          8       1.00      0.25      0.40        28
          9       1.00      0.12      0.22        40

avg / total       0.93      0.42      0.49       360

Confusion Matrix : 
 [[15  0  0 26  0  0  0  0  0  0]
 [ 0 10  0 32  0  0  0  0  0  0]
 [ 0  0  9 36  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0 11 20  0  0  0  0  0]
 [ 0  0  0  8  0 23  0  0  0  0]
 [ 0  0  0 17  0  0 21  0  0  0]
 [ 0  0  0 22  0  0  0 13  0  0]
 [ 0  0  0 21  0  

In [15]:
svc = SVC(kernel='sigmoid')
svc.fit(x_train,y_train)
pred_y = svc.predict(x_test)
print("SVM when Kernel = 'SIGMOID':-\n")
print("Classification Report : \n",smt.classification_report(y_test,pred_y))
print("Confusion Matrix : \n",smt.confusion_matrix(y_test,pred_y))

SVM when Kernel = 'SIGMOID':-

Classification Report : 
              precision    recall  f1-score   support

          0       0.00      0.00      0.00        41
          1       0.00      0.00      0.00        42
          2       0.00      0.00      0.00        45
          3       0.08      1.00      0.15        29
          4       0.00      0.00      0.00        31
          5       0.00      0.00      0.00        31
          6       0.00      0.00      0.00        38
          7       0.00      0.00      0.00        35
          8       0.00      0.00      0.00        28
          9       0.00      0.00      0.00        40

avg / total       0.01      0.08      0.01       360

Confusion Matrix : 
 [[ 0  0  0 41  0  0  0  0  0  0]
 [ 0  0  0 42  0  0  0  0  0  0]
 [ 0  0  0 45  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  0]
 [ 0  0  0 38  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 28  0  0

/home/kritika/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
